### ISSUE TITLE
Request to add features to BoxBuddy

### ISSUE THREAD

**Issue by relbus22** [Dvlv/dbgui#1]
Hi man,
 
Hoping you are well and good.
 
I would like to say that I really like your GUI app for Distrobox, it makes things simpler and I appreciate it very much.
 
I was wondering if there is a way you can add extra features to it? I have three features in mind:
https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#create-a-distrobox-with-a-custom-home-directory
https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#duplicate-an-existing-distrobox
https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#container-save-and-restore
 
I think it'll be really cool.
 
If you ask the r/distrobox sub in reddit, I (and some of the others hopefully) will be able to offer a meager amount for your troubles, nothing substantial but at least something.
 
Cheers.

**Comment by Dvlv** [comment]
Hey there, thanks for opening this issue. I wasn't even sure anyone was using this.

I will have a look at adding some more functionality when I get time. 

FYI I already tried, and failed, to get rootful boxes working, so nothing requiring a rootful box can be added to the GUI.
Those 3 you linked don't seem to need root, so they should be fine.

**Comment by relbus22** [comment]
Jorge Castro; a leading member of the uBlue effort mentioned it, so I'm sure plenty of people saw it:
https://github.com/castrojo/awesome-immutable

Awesome.

**Comment by Dvlv** [comment]
Hey there @relbus22
Those 3 features are now added.

Some Caveats:
- Cloned boxes will have no icon, as the icon is parsed from the image name, and the image of a cloned box is something like `localhost/mybox:2023-05-10`. 
- I was a bit lazy and did not use a Background worker for the Save to File button, so if you're using Gnome it's possible that it will eventually show a "This app is not responding" dialogue. You can ignore that - the command is running, it's just a bit slow.

**Comment by relbus22** [comment]
Hi @Dvlv,

thank you for your work, much appreciated. 

I'm testing the new features on my system right now:
1) Convert-distrobox-to-an-image: check
Is there a BoxBuddy GUI way to restore an image to a distrobox? 
Let's say I want to take my containers to a new PC: 
I can save my distroboxes to a usb, 
install Distrobox and BoxBuddy on the new PC, 
then create new boxes by restoring the gz files from the usb. 

2) Create-a-distrobox-with-a-custom-home-directory: check
3) Clone: check

**Comment by Dvlv** [comment]
Hey, no way to restore from the .tar.gz yet. Will add that next on the Todo

**Comment by relbus22** [comment]
Regarding the custom home, is it possible to make it the default setting by creating a directory? I think that would be better, do you agree? 
Maybe making home/<user>/Containers/<distrobox_name> ??

**Comment by Dvlv** [comment]
I would prefer BoxBuddy's defaults to match those of Distrobox.

**Comment by relbus22** [comment]
okay
